url: https://owenmendez.github.io
baseurl: /whitneycodejam/

# Site settings
title: Owen Mendez
email: owenambrose17@gmail.com
description: "This is my personal website."


# Team names, titles and social links


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/owen._.mendez

  - title: github
    url: http://github.com/owenmendez

# Postal address (add as many lines as necessary)
address:
  - line: Cerritos High School

# Build settings
markdown: kramdown
permalink: pretty
